### ISSUE TITLE
Scale and motion towards the observer

### ISSUE THREAD

**Issue by leapingllamas** [fchollet/ARC#11]
A number of the examples imply motion in 2D plane. I wonder if it would be useful to include simple examples that imply motion in 3D. That is, imagine a input grid with an object and where the output contains the same object scaled up (each pixel of input object become n*n in output, or vice versa) to simulate motion towards or away from the observer.

![Untitled presentation (11)](https://user-images.githubusercontent.com/1386343/69012044-13eb5180-093f-11ea-8286-5b4260a5c1d5.png)

This could also be combined with 2D motion

**Comment by fchollet** [comment]
Upscaling/downscaling (not necessarily related to forward/backward motion) is featured in quite a few tasks.
