### ISSUE TITLE
Does any one solve any task?

### ISSUE THREAD

**Issue by erow** [fchollet/ARC#24]
I can't find any research on this.

**Comment by Alexadar** [comment]
Im sure, to solve one task would mean nothing for a whole idea of general AI. 

Solution for problem would be to create machine which solves all tasks, or majority, f.e. 95%. 

When it will happen, you will be able to read it on sciencedaily or techcrunch.

**Comment by Alexadar** [comment]
> I can't find any research on this.

DARPA pays two billion for AI which would talk to you like 5year kid. Im sure thats why no-one want to share decent research on it.

**Comment by m3at** [comment]
@erow you might want to look at the associated [kaggle challenge](https://www.kaggle.com/c/abstraction-and-reasoning-challenge) where people have been sharing interesting ideas. For example, I find [this approach](https://www.kaggle.com/arsenynerinovsky/cellular-automata-as-a-language-for-reasoning) using cellular automata to be very compelling.

Please note that the source code repository might not be the best place for general discussions, I suggest closing this issue and starting discussions in places like [reddit](https://www.reddit.com/r/MachineLearning/) or the [dataquest community](https://community.dataquest.io/) 🙂 .

**Comment by erow** [comment]
@m3at thank you.
