### ISSUE TITLE
Using the "Random task" button does not show the json filename

### ISSUE THREAD

**Issue by jmmcd** [fchollet/ARC#26]
Load a file normally:
![Screen Shot 2019-12-19 at 20 07 36](https://user-images.githubusercontent.com/167942/71205985-75367580-229b-11ea-9e6b-b01e26efd9fc.png)

Click "Random task":
![Screen Shot 2019-12-19 at 20 07 52](https://user-images.githubusercontent.com/167942/71205984-75367580-229b-11ea-91b1-00e4a4f1f0e9.png)

**Comment by ageron** [comment]
Unfortunately, it's not possible to change the filename next to the "Choose file" button, so I just displayed an info message with the file name when loading it, but the message disappears after a few seconds. It would be nice to fix that.
