### ISSUE TITLE
dc433765.json train 5 == test 0

### ISSUE THREAD

**Issue by leapingllamas** [fchollet/ARC#29]
It seems that dc433765's train 5 == test 0:

```
import json
filename = "../ARC/data/training/dc433765.json"
with open(filename, "r+") as jsonFile:
    data = json.load(jsonFile)
print(data['train'][5]['input'] == data['test'][0]['input'])
print(data['train'][5]['output'] == data['test'][0]['output'])
```
produces
```
True
True
```
![dc433765](https://user-images.githubusercontent.com/1386343/72776592-bdb9b980-3be0-11ea-8f3a-009a548bee2a.png)

**Comment by neoneye** [comment]
wow, `train 5` and `test 0` are indeed the identical.

[ARC-Interactive](https://neoneye.github.io/arc/edit.html?dataset=ARC&task=dc433765)
![dc433765](https://github.com/fchollet/ARC/assets/147971/7b1cbda9-1112-455b-8f32-514e2f634159)
