### ISSUE TITLE
Apparently, 6 tasks seem to have the same implicit goal

### ISSUE THREAD

**Issue by wizeman** [fchollet/ARC#5]
Perhaps I'm simply misunderstanding the paper, but on page 46 it says the following regarding this repository:

> * Focus on measuring developer-aware generalization, rather than task-specific skill, by
> **only featuring novel tasks in the evaluation set**

It also says:

> All tasks are unique, and the set of test tasks and the set of training tasks are disjoint.

I'm not entirely sure what is meant by "disjoint", "novel" or "unique" here (e.g. unique in the sense of the inputs/output pairs being different or unique in the sense that the implicit goal is different?), but I'm guessing the latter.

If so, then I think I found 6 tasks that have the same implicit goal.
They are the following:
```
data/training/ff805c23.json
data/training/dc0a314f.json
data/training/9ecd008a.json
data/evaluation/67b4a34d.json
data/evaluation/f4081712.json
data/evaluation/e66aafb8.json
```
The implicit goal can be described as something like "fill the largest homogeneously-colored rectangle with the pattern that is symmetrically opposite to its location", i.e. basically what is shown on figure 4 of the paper.

I found two of those tasks manually by chance, and to confirm that there was repetition I created a program that solves this particular algorithm and applied it to all the tasks in the public training and evaluation sets.

The program I wrote only tries to solve the task if:
1. All the demonstration inputs have only one homogenously-colored rectangle with the largest area (i.e. it skips the task if multiple homogeneous rectangles with the same largest area are found in one of the demonstration inputs), **and** 
2. The demonstration outputs match (in grid size and grid contents) the output that is expected by this implicit goal.

This relatively simple skipping criteria (which seems to be required anyway, otherwise it would surely fail to solve the test input unless it matched by pure random chance) seems to successfully skip all the publicly-available tasks that are not meant to be solved with this algorithm, as the program never fails on the test inputs that it tries to solve.

If you want to, you can find the actual source code and instructions for compiling and running it here: https://github.com/wizeman/ARC/tree/solve/ocaml

**Important note**: the `data/evaluation/e66aafb8.json` file seems to be the same task that is shown on figure 4 of the paper, so if you end up deciding to delete any of these files for not being unique, I guess you wouldn't want to delete this one!

**Comment by fchollet** [comment]
There can be some overlap between tasks. This should be fine as long as each "genre" only has a few instances in the dataset. Note that your handcrafted program would only do 0.75% accuracy on the evaluation dataset, for instance.

It's a bit unfortunate, though. We'll be more careful in the future.

In any case, consider that:
- ARC is a work in progress. We'll keep adding new tasks and making the current set of tasks more unique.
- The evaluation set is a development set. The real test set is private and will only be able to test your algorithms on it in a competition setting.
